// 上传 QKE 集群安装包

仅安装 QKE v3.0.0 版本需要执行以下操作。

== 背景信息

在私有云部署 QKE 时，IaaS 侧不提供 QKE 所需的 QKE 集群安装包。

所以在部署 QKE 之前需要自行上传 QKE 集群安装包：

* 方式一：上传到云平台对象存储中，提供给用户创建 QKE 集群时下载及安装。
* 方式二：如果没有对象存储，也可以搭建一个文件服务器，将安装包上传到文件服务器中，提供给用户创建 QKE 集群时下载及安装。

== 方式一：上传到对象存储

将link:../../resources/#_qke_资源包[下载的 QKE 集群安装包]（`qke-cli-v3.0.0.tar.gz`、`qke-installer-v3.0.0.tar.gz`）上传到对应对象存储的桶中。例如：有一个对象存储桶叫 qke-plus，直接上传到这个桶的根目录即可。

需确保部署的 QKE 集群可以访问该对象存储的桶。

文件上传到对象存储后，可以在 {product_name} 的 FirstBox 节点执行以下命令，测试是否能通过对象存储下载安装包：

[source]
----
wget <文件链接>
----

== 方式二：上传到文件服务器

如果部署的云平台环境没有对象存储，可以搭建一个文件服务器，然后将link:../../resources/#_qke_资源包[下载的 QKE 集群安装包]（`qke-cli-v3.0.0.tar.gz`、`qke-installer-v3.0.0.tar.gz`）上传到对应目录中即可。

=== 准备云服务器

. 准备一台云服务器（Ubuntu 系统），作为 QKE 的文件服务器。需确保部署的 QKE 集群能够访问到这台服务器。
. 将link:../../resources/#_qke_资源包[下载的 QKE 资源包]（`qke_nginx.tar.gz`、`qke-cli-v3.0.0.tar.gz`、`qke-installer-v3.0.0.tar.gz`）上传到这台云服务器上。

=== 搭建文件服务器

. 登录已上传 QKE 资源包的云服务器。
. 进入 `qke_nginx.tar.gz` 文件所在目录，执行以下命令，解压安装包。
+
[source]
----
tar -zxvf qke_nginx.tar.gz
----

. 执行以下命令，安装文件服务器。
+
[source]
----
cd nginx && ./install.sh
----

=== 上传 QKE 集群安装包

. 在 QKE 文件服务器上执行以下命令，将 `qke-cli-v3.0.0.tar.gz` 和 `qke-installer-v3.0.0.tar.gz` 文件传到 /data/qke 目录下。
+
[source]
----
mkdir /data/qke
mv qke-cli-v3.0.0.tar.gz /data/qke
mv qke-installer-v3.0.0.tar.gz /data/qke
----
. 执行以下命令，测试是否能正常下载安装包。
+
[source]
----
wget 127.0.0.1:8999/qke-cli-v3.0.0.tar.gz
----
+
include::../../../../_components/note.adoc[]
上述命令中 127.0.0.1 为文件服务器的地址，请根据实际情况进行替换。
include::../../../../_components/table_footer.adoc[]
