---
title: 告警列表/详情（Boss2DescribeAlertAggsEvents）
weight: 5
---

== 基本信息

=== Path
/api/?action=Boss2DescribeAlertAggsEvents

=== Method
POST

=== 接口描述
展示汇总后的告警信息。
结果数据：

[.allow_break_inside]
|===
| 字段 | 用途 | 备注

| id
| 告警id，用于后续查询告警的详情
|

| synopsis
| 告警概要
|

| node_id
| 节点id
|

| node_ip
| 节点ip
|

| node_type
| 计算节点/管理节点
|

| node_type_raw
| 未经翻译的node_type
| 0: 计算节点 +
1: 管理节点

| first_notify_time
| 首次告警时间
|

| latest_notify_time
| 告警时间，最近一次告警时间
|

| duration
| 持续时间
|

| alert_type
| [废弃]告警类型
| 该字段将在未来版本中废弃，请及时修改业务代码

| level
| [废弃]告警级别，请使用alert_level字段
| 该字段将在未来版本中废弃，请及时修改业务代码

| status
| 告警的状态
a|

* 0 - 待处理
* 1 - 已处理
* 2 - 已恢复
* 3 - 已忽略
* 4 - 已过期

| read_status
| 阅读状态
| 0 - 未读 +
1 - 已读

| message
| 原始日志信息，详情界面中使用
| 注意原始日志中包含有换行，使用组合字符 \|@@\| 作为换行符

| extra
| 附加信息，有利于分析问题的其他附加信息
| 附加信息是一个字典结构，目前不做翻译，直接将其中的数据进行展示即可

| notify_policy_id
| [废弃]监控项id，请使用alert_category_id
| 该字段将在未来版本中废弃，请及时修改业务代码

| notify_policy_verbose_name
| [废弃]监控项名称，请使用alert_category_name
| 该字段将在未来版本中废弃，请及时修改业务代码

| notify_policy_suggestion
| [废弃]告警处理方案，请使用alert_handling
| 该字段将在未来版本中废弃，请及时修改业务代码

| handling_note
| 处理意见
|

| recipient
| 接收告警的通知组
| id: 通知组id +
name: 通知组名称

| alert_code
| 告警编号
|

| alert_pattern_id
| 告警匹配规则的id
|

| alert_description
| 告警描述
|

| alert_reason
| 可能原因
|

| alert_influence
| 影响范围
|

| alert_handling
| 告警处理方法
| 该部分数据为html格式

| alert_level
| 级别
a|
该部分数据取代之前的level字段，可能的取值有：

* CRITICAL
* ERROR
* WARNING
* INFO

| alert_source_id
| 告警来源ID
|

| alert_source_name
| 告警来源名称
|

| alert_category_id
| 告警类型ID
|

| alert_category_name
| 告警类型名称
|

| self_healing
a|
告警可否自愈

* true - 可自愈
* false - 不可自愈
|
|===


== 请求参数

*Headers*

[cols="3*", options="header"]

|===
| 参数名称 | 参数值 | 是否必须

| Content-Type
| application/json
| 是
|===

*Body*

[,javascript]
----
{
  "action": "Boss2DescribeAlertAggsEvents",
  
  // 分页及排序
  "limit": 1, // 限制返回数据条数，设置为0仅返回数据总条数
  "offset": 0, // 数据offset，与limit结合进行分页
  "sort_key": "latest_notify_time", // 指定用于排序的字段
  "reverse": 1, // 是否进行逆序,1-逆序，其他值为顺序，
  "search_word": "异常退出", // 用于部分字段的模糊搜索
  "fields": ["id", "alert_type"], // 用于返回数据的过滤，仅返回列表中指定的字段数据
  
  // 以下参数用于筛选
  "zone": "test", // 指定zone，如不指定将返回所有zone的数据
  "id": [1], // 获取指定id的告警信息，用于详情展示
  "status": [2], // 获取指定状态的告警信息
  "read_status": [0], // 获取未读(0)和已读状态(1)的告警信息
  "node_type": [1], // 指定节点类型
  "node_id": ["webservice0"], // 指定告警发生的节点id
  "alert_levels": ["CRITICAL"], // 通过告警级别进行过滤
  "alert_categories": ["bba8ace4-a108-4dfe-aff0-f0578812b16f"], // 通过告警类型ID进行过滤
  "alert_sources": ["IAAS"], // 通过告警来源进行过滤
  "start_time": "2019-01-21T01:36:01.938Z", // 指定起始时间
  "end_time": "2019-01-21T02:36:01.938Z" // 指定结束时间
}
----

== 返回数据

[,javascript]
----
{
  "alert_set": [
    {
      "id": 1,
      "zone_id": "test",
      "synopsis": "计算节点负载过高",
      "node_id": "tr02n19",
      "node_ip": "172.0.16.2",
      "node_type": "计算节点",
      "first_notify_time": "2020-06-08T02:36:32Z",
      "latest_notify_time": "2020-06-08T02:36:32Z",
      "duration": 3610,
      "alert_type": "服务异常",
      "level": "WARNING",
      "status": 0,
      "message": "[test] [tr02n12] has alerts |@@|=== compute_agent.log.wf ===|@@|2019-01-08 15:31:22,622 CRITICAL -140164152149760- hyper load is high: [15] (/pitrix/lib/pitrix-bots/bot/compute/agent/inspector/hypernode.py:268)",
      "extra": {
        "datetime": "2019-01-08 15:31:22,622",
        "load_average": "15"
      },
      "notify_policy_id": 1,
      "notify_policy_verbose_name": "节点负载过高",
      "notify_policy_suggestion": "重启节点即可",
      "notify_policy_recipient": [
        {
          "id": 1,
          "name": "test1",
          
        },
        {
          "id": 2,
          "name": "test2",
          
        }
      ],
      "handling_note": null,
      "handling_time": null,
      "alert_code": "ALM-ECS-00002",
      "alert_pattern_id": "febaa687-557a-4d1f-b53a-4bbba84e349c",
      "alert_description": "告警模块会检测计算节点负载，当发现负载超过阈值时，会产生此告警。",
      "alert_reason": "可能原因：1. 硬件故障 2. 物理机中毒",
      "alert_influence": "影响该hyper上虚拟资源的性能",
      "alert_handling": "<p>资源迁移走, 再尝试修复物理机</p>",
      "alert_level": "CRITICAL",
      "alert_source_id": "ECS",
      "alert_source_name": "弹性云主机",
      "alert_category_id": "bba8ace4-a108-4dfe-aff0-f0578812b16f",
      "alert_category_name": "节点宕机或故障",
      "self_healing": true,
    }
  ],
  "total_count": 1,
  "ret_code": 0,
  "action": "Boss2DescribeAlertAggsEventsResponse"
}
----
