---
title: "IAM 简介"
weight: 10
---
*IAM（Identity and Access Management：访问鉴权管理）* 是一款在{platform_name_cn}上提供身份识别和访问控制的 Web 服务。 IAM 将{platform_name_cn}各模块的操作 API 纳管并定义了各类服务及资源之间的关系，由客户自行编辑策略以组合成不同操作权限的集合后赋予给其他身份，最终实现对该客户的服务或资源接入控制统一管理。通过使用 IAM 来统一管理和控制接入实体的认证和授权，能更安全地自主管控本账户下的任意资源访问权限。

青云 IAM 旨在统一构建{platform_name_cn}的权限管理标准。它采用非对称加密技术创建具备一定访问时效的临时 Token 为访问者赋予身份凭证，无需引入 Access Key 且身份的使用者可以是人、设备、应用等任何支持获取凭证 Token 的实体。当客户需要为他人或者应用赋予自己资源的访问权限时，可以随心的配置任意粒度的权限和身份载体，不必再共享访问密钥。从而做到对接入实体的全方位统一管控，极大降低访问密钥被泄露的风险，提高平台客户信息的安全性。

*身份：* 身份是使用策略（集）的操作者；身份可以被其它账户或者资源带入，这个时候我们需要将策略绑定到身份上面来控制此身份的权限。

*策略：* 您可以通过 IAM 策略定义一系列服务或资源的访问权限范围，然后将其引用到指定的身份上。策略定义了一系列权限，以 JSON 的方式呈现。

*预置策略：* 预置策略是 IAM 平台提供或第三方制定并添加到 IAM 中的 “默认” 策略，便于 IAM 使用这快速对身份附加策略，一般一直策略由管理员创建，{platform_name_cn}用户直接选择附加即可。

*信任载体：* 被身份信任的使用实体叫做信任载体，只有信任载体才能代入该身份。

*QRN：* {platform_name_cn}资源名称（QRN）被用来作为{platform_name_cn}资源的唯一标识。当您需要在全局环境（比如 IAM 策略）中明确指定一项资源时，我们要求使用 QRN。

== IAM 的作用与特点

=== 共享访问

您可以通过配置 IAM ，向您的{platform_name_cn}资源或其他{platform_name_cn}账户授予权限来管理和使用您账户中的资源，而不必共享您的账户密码或 API Access Key。

例如，您可以允许您的主机中创建的应用通过集成{platform_name_cn}官方 SDK 获取身份凭证信息，随后即可在应用中直接调用{platform_name_cn} API/CLI 以访问其他资源。

=== 精细权限

您可以通过配置 IAM ，向不同的身份实体授予不同的资源访问权限。

例如，您可以允许您的子账户 A 通过代入您赋予的身份完全访问您账户中的弹性云主机服务（支持创建、启停或销毁主机等），而同时允许{platform_name_cn}系统中的另一个账户 B 通过代入您赋予的身份仅具备查看某个特定主机信息的权限。

